name: i_am_rich
description: "A new Flutter project."

publish_to: 'none'


version: 1.0.0+1

environment:
  sdk: ^3.10.1

dependencies:
  flutter:
    sdk: flutter
  auto_size_text: ^3.0.0
  mesh_gradient: ^1.3.8
  http: ^1.1.0
  uuid: ^4.2.1

  cupertino_icons: ^1.0.8
  form_builder_validators: ^11.2.0
  mask_text_input_formatter: ^2.9.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^6.0.0

flutter:


  uses-material-design: true

  assets:
      - images/
      - lib/icons/

  fonts:
      - family: Pacifico
        fonts:
          - asset: fonts/Pacifico-Regular.ttf

